---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: pgsql01
    box: ${MOLECULE_DISTRO:-"generic/debian10"}
    groups: 
      - pgpool
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
    memory: 1024
    cpus: 1
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.30.10
        auto_config: true
  - name: pgsql02
    box: ${MOLECULE_DISTRO:-"generic/debian10"}
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
    groups: 
      - pgpool
    memory: 1024
    cpus: 1
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.30.11
        auto_config: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: "profile_tasks,timer"
      allow_world_readable_tmpfiles: true
      ansible_python_interpreter: /usr/bin/python3
  inventory:
    host_vars:
      pgsql01:
        # ansible
        ansible_host: 192.168.30.10
        # repmgr
        repmgr_node_id: 1 
        # pgpool
        pgpool_wd_hostname: pgsql01
        pgpool_wd_priority: 1
        # watchdog
        pgpool_heartbeat_destination:
          - hostname: pgsql02
        pgpool_other_settings: 
          - hostname: pgsql02
      pgsql02:
        # ansible
        ansible_host: 192.168.30.11
        # repmgr
        repmgr_node_id: 2
        pgpool_wd_hostname: pgsql02
        pgpool_wd_priority: 2
        # watchdog
        pgpool_heartbeat_destination:
          - hostname: pgsql01
        pgpool_other_settings: 
          - hostname: pgsql01
