---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    pgpool_delegate_IP: 192.168.30.30
    pgpool_port: 9999
    pgpool_pcp_port: 9898
    pgpool_passwd_users_md5: 
      - username: admin
        password: secret
    pgpool_user: pgpool

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Ensure pgpool2 version matches pgpool_version_debian
      assert: 
        that: ansible_facts.packages['pgpool2'][0]['version'] == pgpool_version_debian
        success_msg: Installed pgpool2 version '{{ ansible_facts.packages['pgpool2'][0]['version'] }}' matches pgpool_version_debian 
        fail_msg: There is mismatch between the expected and the installed version!

    - name: Start Pg-Pool II
      systemd: 
        name: pgpool2
        state: started

    - name: Ensure PgPool port is running
      wait_for: 
        host: 0.0.0.0
        port: "{{ pgpool_port }}"

    - name: Ensure PCP port is running
      wait_for: 
        host: 0.0.0.0
        port: "{{ pgpool_pcp_port }}"

    - name: Show POOL_NODES
      postgresql_query:
        login_host: "{{ pgpool_delegate_IP }}"
        login_user: "{{ pgpool_passwd_users_md5[0].username }}"
        db: testdb
        port: "{{ pgpool_port }}"
        query: "SHOW POOL_NODES"
      register: pool_status

    - name: Output pool status
      debug:
        msg:
          "pool_status": "{{ pool_status.query_result }}"

    - name: Get Watchdog info
      shell:
        cmd: pcp_watchdog_info -h 127.0.0.1 -U pgpool -wv
      become_user: "{{ pgpool_user }}"
      register: watchdog_status

    - name: Output watchdog status
      debug:
        msg:
          "watchdog_status": "{{ watchdog_status.stdout_lines }}"
